#! /bin/sh

CASE=$1 #veg_stan_od 

# ./$CASE.exe sample num_samples=5 num_warmup=15 data file=../r/dump/cal_data_12taxa_mid_comp_v0.1.dump output file=$CASE.csv random seed=42


./$CASE.exe sample num_samples=5 num_warmup=15 data file=../r/dump/cal_data_12taxa_mid_comp_ALL_v0.3.dump output file=$CASE.csv random seed=42
